_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
login:
    path:     /admin/login/
    defaults: { _controller: AppBundle:Security:login }
forgetpwd:
    path:     /admin/forgetpwd/
    defaults: { _controller: AppBundle:Security:forgetpwd }
login_check:
    path: /admin/login_check/
logout:
    path: /admin/logout/
admin_index:
    path:     /admin/
    defaults: { _controller: AppBundle:Admin:index }
admin_member:
    path:     /admin/member/
    defaults: { _controller: AppBundle:Admin:Member }
admin_bind_member:
    path:     /admin/member/bind/
    defaults: { _controller: AppBundle:Admin:Member, bind: 'yes'}
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
bushidoio_qrcode:
    resource: "@BushidoIOQRCodeBundle/Controller/"
    type:     annotation
