# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    knp_menu.renderer.twig.options:
            currentClass: active

services:
    listener.wechat:
         class: AppBundle\EventListener\OAuthListener
         arguments: [ "@router", "@service_container" ]
         tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
           #- { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
           #- { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]